### ISSUE TITLE
norm

### ISSUE THREAD

**Issue by yu-432** [yu-432/minishell-ryomori-yooshi#110]
## Overview
ノームに適合させる

## Purpose
バッシュくんのため

## Task
Break down and manage your tasks.
- [x] take_env_name に含まれるstrlenの変更
- [ ] expand_dollar ft_strjoinのエラー処理
- [x] マジックナンバーを無くす
- [x] set_exit_status ダンプファイルは生成されないためquitの方が適切
- [x] (void)を使用しなくていいように引数の確認をする
- [x] ./minishell hello など引数の対策

**Comment by yu-432** [comment]
mallocエラー処理以外について実装した
後日エラー処理を実装します。
